name: Actions testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Javascript Tools
        uses: Swanseatom/js-dynamic-methods-action@v1.0.0
        if: js-dynamic-methods
        with:
          value: item1, item2, item3, item4
          type: string
          method: split
          args: ","
          argTypes: string
          envVar: MY_ENV_VAR
      - name: test env var is set
        run: echo "${{env.MY_ENV_VAR}}"
      - name: test step output is set
        run: echo "${{steps.js-dynamic-methods.outputs.result}}"
